version: '3'
services:
  postgres:

    image: postgres:16.2
    container_name: db

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=dbname
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pgdata:/var/lib/postgresql/data


  myapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres